# -*- coding: utf-8 -*-
"""Health AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Loe0VTbd8WvI56zmppXfJWQPqhSeLaH
"""

!pip install transformers torch gradio -q

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import gradio as gr

# IBM Granite Model load பண்ணுது
model_name = "ibm-granite/granite-3.2-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map="auto")

def health_ai_chat(user_input):
    inputs = tokenizer(user_input, return_tensors="pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens=200)
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

with gr.Blocks() as demo:
    gr.Markdown("# 🏥 Health AI - Intelligent Healthcare Assistant")
    chatbot = gr.ChatInterface(fn=health_ai_chat)

demo.launch()